version: '3'
services:
  keeper-node:
    container_name: nevermined-keeper-node
    image: trufflesuite/ganache-cli:latest
    command:
      ${GANACHE_COMMAND_OPTIONS:--d}
    ports:
      - ${KEEPER_RPC_PORT:${KEEPER_RPC_PORT}
    networks:
      backend:
        ipv4_address: 172.15.0.12
