version: '3'
services:
  keeper-node:
    container_name: nevermined-keeper-node
    image: ${PARITY_IMAGE}
    user: root
    command:
      --config /home/parity/parity/config/config.toml
      --base-path /home/parity/base
      --keys-path /keys
      --ws-interface all
      --jsonrpc-cors all
      --jsonrpc-interface all
      --jsonrpc-hosts all
      --jsonrpc-apis all
    volumes:
      - ../networks/integration/config:/home/parity/parity/config
      - ../networks/integration/keys:/keys/integration
      - keeper-node-integration:/home/parity/base
    ports:
      - 8545:8545
    networks:
      backend:
        ipv4_address: 172.15.0.12
