version: "3"
services:
  keeper-node:
    container_name: nevermined-keeper-node
    image: neverminedio/polygon-localnet:${KEEPER_VERSION}
    user: root
    command: --dev
      --chain genesis.json
      --data-dir test-chain
      --jsonrpc 0.0.0.0:8545
    volumes:
      - ${KEEPER_ARTIFACTS_FOLDER}:/nevermined-contracts/artifacts/
      - ${KEEPER_CIRCUITS_FOLDER}:/nevermined-contracts/circuits/
    ports:
      - 8545:8545
    networks:
      backend:
        ipv4_address: 172.15.0.12
