version: '3'
services:
  aquarius:
    image: oceanprotocol/aquarius:$AQUARIUS_VERSION
    ports:
    - 5000:5000
    networks:
      backend:
        ipv4_address: 172.15.0.15
    environment:
      DB_MODULE: ${DB_MODULE}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSL: ${DB_SSL}
      DB_VERIFY_CERTS: ${DB_VERIFY_CERTS}
      DB_CA_CERTS: ${DB_CA_CERTS}
      DB_CLIENT_KEY: ${DB_CLIENT_KEY}
      DB_CLIENT_CERT: ${DB_CLIENT_CERT}
