version: '3'
services:
  elasticsearch:
    container_name: nevermined-elasticsearch
    image: elasticsearch:7.13.2
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      backend:
        ipv4_address: 172.15.0.11
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      MAX_MAP_COUNT: "64000"
      discovery.type: "single-node"
