version: '3'
services:
  events-handler:
    image: oceanprotocol/events-handler:$EVENTS_HANDLER_VERSION
    networks:
      backend:
        ipv4_address: 172.15.0.22
    depends_on:
      - keeper-node
    environment:
      KEEPER_URL: ${KEEPER_RPC_URL}
      PARITY_URL: ${SIGNING_NODE_URL}
      SECRET_STORE_URL: ${SECRET_STORE_URL}
      PROVIDER_ADDRESS: ${PROVIDER_ADDRESS}
      PROVIDER_PASSWORD: ${PROVIDER_PASSWORD}
      PROVIDER_KEYFILE: ${PROVIDER_KEYFILE}
      LOCAL_CONTRACTS: ${KEEPER_DEPLOY_CONTRACTS}
      LOG_LEVEL: ${EVENTS_HANDLER_LOG_LEVEL}
    volumes:
      - ${KEEPER_ARTIFACTS_FOLDER}:/usr/local/keeper-contracts:ro
      - ${ACCOUNTS_FOLDER}:/accounts
