version: '3'
services:
  mongodb:
    image: mongo:4
    ports:
      - 27017:27017
    networks:
      backend:
        ipv4_address: 172.15.0.20

  faucet:
    image: oceanprotocol/faucet:$FAUCET_VERSION
    ports:
      - 3001:3001
    networks:
      backend:
        ipv4_address: 172.15.0.21
    depends_on:
      - mongodb
      - keeper-node
    environment:
      FAUCET_NODE: ${KEEPER_RPC_URL}
      FAUCET_TIMESPAN: ${FAUCET_TIMESPAN}
      NODE_ENV: 'production'
      MONGO_URL: 'mongodb://mongodb:27017/faucetdbtest'
