version: '3'
services:
  node:
    container_name: nevermined-node
    image: neverminedio/node:$NODE_VERSION
    ports:
      - 8030:8030
    networks:
      backend:
        ipv4_address: 172.15.0.17
    depends_on:
      - keeper-node
    env_file:
      - ${NODE_ENV_FILE}
    environment:
      WEB3_PROVIDER_URL: ${WEB3_PROVIDER_URL}
      NODE_ADDRESS: ${PROVIDER_ADDRESS}
      PROVIDER_PASSWORD: ${PROVIDER_PASSWORD}
      PROVIDER_KEYFILE: ${PROVIDER_KEYFILE}
      RSA_PRIVKEY_FILE: ${RSA_PRIVKEY_FILE}
      RSA_PUBKEY_FILE: ${RSA_PUBKEY_FILE}
      LOG_LEVEL: ${NODE_LOG_LEVEL}
      NODE_WORKERS: ${NODE_WORKERS}
      IPFS_GATEWAY: ${NODE_IPFS_GATEWAY}
      IPFS_PROJECT_ID: ${IPFS_PROJECT_ID}
      IPFS_PROJECT_SECRET: ${IPFS_PROJECT_SECRET}
      COMPUTE_API_URL: ${COMPUTE_API_URL}
      AUTHLIB_INSECURE_TRANSPORT: ${AUTHLIB_INSECURE_TRANSPORT}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      ESTUARY_TOKEN: ${ESTUARY_TOKEN}
      ESTUARY_ENDPOINT: ${ESTUARY_ENDPOINT}
    volumes:
      - ${KEEPER_ARTIFACTS_FOLDER}:/artifacts
      - ${KEEPER_CIRCUITS_FOLDER}:/circuits
      - ${ACCOUNTS_FOLDER}:/accounts
