version: '3'
services:
  secret-store-signing-node:
    container_name: nevermined-secret-store-signing-node
    image: ${OPENETH_IMAGE}:${OPENETH_VERSION}
    command:
      --chain dev
      --ws-interface all
      --jsonrpc-cors all
      --jsonrpc-interface all
      --jsonrpc-hosts all
      --jsonrpc-apis all
      --keys-path /home/openethereum/.local/keys
    ports:
      - 9545:8545
    volumes:
      - ../networks/secret-store/keys:/home/openethereum/.local/keys
      - ../networks/secret-store/config/:/etc/openethereum/secret-store/
    networks:
      backend:
        ipv4_address: 172.15.0.18
