# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Nevermined Tools

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install minikube v1.22.0
      run: |
        wget https://storage.googleapis.com/minikube/releases/v1.22.0/minikube-linux-amd64
        chmod +x minikube-linux-amd64
        sudo mv minikube-linux-amd64 /usr/local/bin/minikube

    - name: Reclaim some disk space
      run : |
          docker system prune --all --volumes -f

    - name: Test
      run: |
        docker login -u ${{ secrets.NEVERMINED_DOCKER_USERNAME }} -p ${{ secrets.NEVERMINED_DOCKER_TOKEN}}
        rm -rf "${HOME}/.nevermined/nevermined-contracts/artifacts"

        # start nevermined with the compute stack
        ./start_nevermined.sh --latest --spree-embedded-contracts &

        # wait for the compute api to be online.
        # the compute api is the last service to come online
        ./scripts/wait-subgraphs.sh
